# Generated by Django 4.2.7 on 2023-12-20 16:40

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, max_length=50000, null=True, upload_to='images/blogs')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
