# Generated by Django 4.2.7 on 2023-11-20 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, max_length=50000, null=True, upload_to='images/products')),
                ('name', models.CharField(max_length=500)),
                ('typeProduct', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=500)),
                ('pricesale', models.CharField(default=models.CharField(max_length=500), max_length=500)),
                ('description', models.CharField(max_length=100000)),
                ('onSale', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
