# Generated by Django 4.2.3 on 2023-08-15 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=100000)),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=100000)),
            ],
        ),
    ]
