# Generated by Django 4.2.7 on 2023-12-20 16:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Types',
            fields=[
                ('product_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=100000)),
                ('price', models.CharField(max_length=500)),
                ('pricesale', models.CharField(default=models.CharField(max_length=500), max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(default=0)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_types')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('product_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.ImageField(blank=True, max_length=50000, null=True, upload_to='images/products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
