# Generated by Django 4.2.3 on 2023-08-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricesale',
            field=models.CharField(default=100, max_length=500),
            preserve_default=False,
        ),
    ]
