# Generated by Django 4.2.3 on 2023-08-17 17:24

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_title_product_name_product_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
    ]
