# Generated by Django 4.2.3 on 2023-08-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_image_remove_product_image_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=50000, null=True, upload_to='images/products/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
