# Generated by Django 4.2.3 on 2023-08-21 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_images_product_image_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=50000, null=True, upload_to='images/'),
        ),
    ]
