# Generated by Django 4.2.3 on 2023-08-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_createdat_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='onSale',
            field=models.BooleanField(default=False),
        ),
    ]
