# Generated by Django 4.2.3 on 2023-10-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_delete_post_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pricesale',
            field=models.CharField(default=models.CharField(max_length=500), max_length=500),
        ),
    ]
